### ISSUE TITLE
Bug Report: Plugin Crash with beta12 and Roomba 960

### ISSUE THREAD

**Issue by NateUT99** [bloomkd46/homebridge-iRobot#104]
### Describe The Bug:

I noticed this with beta 11 as well, but I am getting a plugin crash every few minutes. I have tried using both manual configuration and cloud connection, but get the same behavior. During this time the Roomba remains in the "No Response" state and is not controllable via the Home app.

### To Reproduce:

Install beta, restart child bridge, wait a few minutes.

### Expected behavior:

The plugin would not crash and the Roomba would be controllable via HomeKit.

### Logs:

```shell
[03/03/2022, 08:23:50] [iRobot] Restarting Process...
[03/03/2022, 08:23:51] [iRobot] Launched child bridge with PID 23897
[3/3/2022, 8:23:52 AM] Registering platform 'homebridge-irobot.iRobotPlatform'
[03/03/2022, 08:23:53] [iRobot] Loaded homebridge-irobot v3.0.0-beta.12 child bridge successfully
[3/3/2022, 8:23:53 AM] Loaded 1 cached accessories from cachedAccessories.0EA28718C32A.
[3/3/2022, 8:23:53 AM] [iRobot] Loading accessory from cache: Roomba
[3/3/2022, 8:23:53 AM] [iRobot] Logging into iRobot...
[3/3/2022, 8:23:53 AM] Homebridge v1.4.0 (HAP v0.10.0) (iRobot) is running on port 42855.
[3/3/2022, 8:23:54 AM] [iRobot] Succefully logged into iRobot
[3/3/2022, 8:23:54 AM] [iRobot] Restoring existing accessory from cache: Roomba
[3/3/2022, 8:25:03 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:03 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:03 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:03 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:03 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Contact Sensor State' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:08 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:08 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:08 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:08 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:08 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Contact Sensor State' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:09 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:09 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:09 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:09 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:09 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Contact Sensor State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:14 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:14 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:14 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:14 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:25:14 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Contact Sensor State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:26:06 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:26:06 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:26:06 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:26:06 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:26:06 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Contact Sensor State' was slow to respond! See https://git.io/JtMGR for more info.
[3/3/2022, 8:26:12 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:26:12 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:26:12 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:26:12 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:26:12 AM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Contact Sensor State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[3/3/2022, 8:27:24 AM] [iRobot] [Roomba] Failed To Update State:
 Roomba Offline
TypeError: Cannot read properties of undefined (reading 'end')
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-irobot/src/V2/RoombaController.ts:87:23)
    at MqttClient.emit (node:events:520:28)
    at MqttClient._setupReconnect (/usr/local/lib/node_modules/homebridge-irobot/node_modules/mqtt/lib/client.js:730:12)
    at MqttClient._cleanUp (/usr/local/lib/node_modules/homebridge-irobot/node_modules/mqtt/lib/client.js:775:10)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-irobot/node_modules/mqtt/lib/client.js:327:10)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
[03/03/2022, 08:28:24] [iRobot] Child bridge process ended
[03/03/2022, 08:28:24] [iRobot] Process Ended. Code: 1, Signal: null
[03/03/2022, 08:28:31] [iRobot] Restarting Process...
[03/03/2022, 08:28:32] [iRobot] Launched child bridge with PID 27187
[3/3/2022, 8:28:33 AM] Registering platform 'homebridge-irobot.iRobotPlatform'
[03/03/2022, 08:28:33] [iRobot] Loaded homebridge-irobot v3.0.0-beta.12 child bridge successfully
[3/3/2022, 8:28:33 AM] Loaded 1 cached accessories from cachedAccessories.0EA28718C32A.
[3/3/2022, 8:28:33 AM] [iRobot] Loading accessory from cache: Roomba
[3/3/2022, 8:28:34 AM] [iRobot] Logging into iRobot...
[3/3/2022, 8:28:34 AM] Homebridge v1.4.0 (HAP v0.10.0) (iRobot) is running on port 42855.
[3/3/2022, 8:28:35 AM] [iRobot] Succefully logged into iRobot
[3/3/2022, 8:28:35 AM] [iRobot] Restoring existing accessory from cache: Roomba
```

### Config:

```shell
{
            "name": "iRobot",
            "email": "redacted",
            "password": "redacted",
            "manualDiscovery": false,
            "lowBattery": 20,
            "offAction": "pause:dock",
            "status": "phase:run",
            "sensors": [
                {
                    "type": "contact",
                    "condition": "binFull:true"
                }
            ],
            "_bridge": {
                "username": "0E:A2:87:18:C3:2A",
                "port": 42855
            },
            "platform": "iRobotPlatform"
        },
```

### Node Version:

v16.14.0

### NPM Version:

8.3.1

### Homebridge Version:

1.4.0

### Plugin Version:

homebridge-irobot@3.0.0-beta.12

### Operating System:

Raspberian

**Comment by NateUT99** [comment]
Not entirely sure what has changed, but the plugin has been working as expected for the past 36 hours. I have tried to get it to throw any of the messages or errors that are present in the main report, but the device has been responsive. Based on this, I am going to go ahead and close this report and will reopen another if necessary.
