### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by Yarrlm** [bloomkd46/homebridge-iRobot#124]
### Describe Your Problem:

i am new to this so please forgive me if i do a step wrong.
Thanks for the creation of this though it is really be educational.
ok on to the issue
5/24/2022, 9:00:37 AM] [Robbie] Failed to configure roomba: Robbie see below for details
[5/24/2022, 9:00:37 AM] [Robbie] No Roomba Found With Blid: 060522ECA9A24CC7816F680F7519EB99

Not sure why i am getting this error

### Expected behavior:

Successful installation

### Logs:

```shell
5/24/2022, 9:00:37 AM] [Robbie] Failed to configure roomba: Robbie see below for details
[5/24/2022, 9:00:37 AM] [Robbie] No Roomba Found With Blid: 060522ECA9A24CC7816F680F7519EB99
```

### Config:

```shell
name": "Robbie",
            "email": "yarrlm@yahoo.com",
            "password": "***************",
            "roombas": [
                {
                    "autoConfig": true,
                    "info": {
                        "ver": 2
                    }
                }
            ],
            "manualDiscovery": false,
            "lowBattery": 20,
            "offAction": "pause:dock",
            "status": "cycle:clean",
            "eveStatus": "inverted:cycle:clean",
            "bin": "filter:contact",
            "ignoreMultiRoomBin": true,
            "hideStuckSensor": false,
            "disableMultiRoom": false,
            "platform": "iRobotPlatform"
        },
```

### Node Version:

v16.15.0

### NPM Version:

not sure 

### Homebridge Version:

v1.4.1

### Plugin Version:

homebridge-irobot v2.1.16

### Operating System:

Other

**Comment by bloomkd46** [comment]
Please try the latest beta: [![npm](https://img.shields.io/npm/v/homebridge-irobot/beta?label=beta)](https://github.com/bloomkd46/homebridge-iRobot/wiki/Beta-Version)

**Comment by Yarrlm** [comment]
Thank you for the reply.
I tried the beta but it failed with Homebridge

[1/2/2023, 11:55:41 AM] TypeError: this.config.accessories is not iterable
    at iRobotPlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-irobot/src/platform.ts:101:38)
    at HomebridgeAPI.<anonymous> (/volume1/homebridge/node_modules/homebridge-irobot/src/platform.ts:60:12)
    at HomebridgeAPI.emit (node:events:539:35)
    at HomebridgeAPI.signalFinished (/volume1/homebridge/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/volume1/homebridge/node_modules/homebridge/src/server.ts:190:14)
[1/2/2023, 11:55:41 AM] Got SIGTERM, shutting down Homebridge...
[1/2/2023, 11:55:41 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet!
    at Bridge.Accessory.setupURI (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11)
    at Server.setServerStatus (/volume1/homebridge/node_modules/homebridge/src/server.ts:155:45)
    at Server.teardown (/volume1/homebridge/node_modules/homebridge/src/server.ts:199:10)
    at signalHandler (/volume1/homebridge/node_modules/homebridge/src/cli.ts:93:12)
    at process.emit (node:events:527:28)
    at process.emit (/volume1/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
[1/2/2023, 11:55:41 AM] [TplinkSmarthome] Child bridge process ended
[1/2/2023, 11:55:41 AM] [homebridge-samsung-tizen] Child bridge process ended

**Comment by bloomkd46** [comment]
> Thank you for the reply. I tried the beta but it failed with Homebridge
> 
> [1/2/2023, 11:55:41 AM] TypeError: this.config.accessories is not iterable at iRobotPlatform.discoverDevices (/volume1/homebridge/node_modules/homebridge-irobot/src/platform.ts:101:38) at HomebridgeAPI. (/volume1/homebridge/node_modules/homebridge-irobot/src/platform.ts:60:12) at HomebridgeAPI.emit (node:events:539:35) at HomebridgeAPI.signalFinished (/volume1/homebridge/node_modules/homebridge/src/api.ts:275:10) at Server.start (/volume1/homebridge/node_modules/homebridge/src/server.ts:190:14) [1/2/2023, 11:55:41 AM] Got SIGTERM, shutting down Homebridge... [1/2/2023, 11:55:41 AM] AssertionError [ERR_ASSERTION]: Cannot generate setupURI on an accessory that isn't published yet! at Bridge.Accessory.setupURI (/volume1/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:994:11) at Server.setServerStatus (/volume1/homebridge/node_modules/homebridge/src/server.ts:155:45) at Server.teardown (/volume1/homebridge/node_modules/homebridge/src/server.ts:199:10) at signalHandler (/volume1/homebridge/node_modules/homebridge/src/cli.ts:93:12) at process.emit (node:events:527:28) at process.emit (/volume1/homebridge/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21) [1/2/2023, 11:55:41 AM] [TplinkSmarthome] Child bridge process ended [1/2/2023, 11:55:41 AM] [homebridge-samsung-tizen] Child bridge process ended

fixed v4.0.0-beta.3

**Comment by Yarrlm** [comment]
Well.......Good News is this is a lot father then it was before.
It looks like the device was found and i was able to put the static IP in place now.
[1/2/2023, 2:29:00 PM] [Robbie] Robbie: undefined 
[1/2/2023, 2:29:00 PM] [Robbie] Robbie: Offline 

Not sure why he says Offline now though because he is currently running a job.

But I do see the error below.  By the way thank you for the time you have put into this.

However when rebooting i see the following error now:
[1/2/2023, 2:29:03 PM] [homebridge-irobot] This plugin threw an error from the characteristic 'Status Low Battery': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'batPct'). See https://homebridge.io/w/JtMGR for more info.
[1/2/2023, 2:29:03 PM] [homebridge-irobot] This plugin threw an error from the characteristic 'Battery Level': Unhandled error thrown inside read handler for characteristic: Cannot read properties of undefined (reading 'batPct'). See https://homebridge.io/w/JtMGR for more info.
[1/2/2023, 2:29:03 PM] [homebridge-irobot] This plugin threw an error from the characteristic 'Charging State': Unhandled error thrown inside read handler for characteristic: Cannot use 'in' operator to search for 'cleanMissionStatus' in undefined. See https://homebridge.io/w/JtMGR for more info.

**Comment by bloomkd46** [comment]
Offline means that when it tried to ping the ip you provided their was no response

**Comment by bloomkd46** [comment]
Make sure that you double check the ip address you configured

**Comment by Yarrlm** [comment]
Yes, The IP is correct according to the IRobot App and the Unifi router, it is a static IP

**Comment by bloomkd46** [comment]
Last I checked, the iRobot app shows the external IP address, not the local one that the plugin needs. It should be something like `10.0.0.x` or `192.168.1.x`

**Comment by Yarrlm** [comment]
The IRobot is showing the same IP as the local one. 192.168.20.159
![IMG_0494](https://user-images.githubusercontent.com/106166331/210283642-94d7d812-e642-42a0-ac47-850509256ff0.png)

**Comment by bloomkd46** [comment]
Could you try running `ping 192.168.20.159` from the terminal in homebridge

**Comment by Yarrlm** [comment]
Sorry, I am not able to figure out how to get it to ping. I run this on my Synology with docker

**Comment by bloomkd46** [comment]
https://user-images.githubusercontent.com/75853497/210290778-9b7db175-87fe-4b95-9733-b0bc6b5cd774.MOV
