### ISSUE TITLE
Bug Report: spelling error results in crash

### ISSUE THREAD

**Issue by rcoletti116** [bloomkd46/homebridge-iRobot#18]
### Describe The Bug:

Homebridge crashes on getRoombaIP.js. Logs indicate a reference error for "proccess.argv" where process is spelled wrong. Changing to "process.argv" resolves the crash.

Change at lines 9 & 12 of getRoombaIP.js.

Logs below.

### To Reproduce:

Enable plugin, restart homebridge.

### Expected behavior:

Homebridge loads plugin successfully.

### Logs:

```shell
[06/01/2022, 15:38:16] [redacted] Getting IP address for roomba: Rosie
/usr/local/lib/node_modules/homebridge-irobot/dist/scripts/getRoombaIP.js:9
const attempt = proccess.argv[3] || 1;
                ^

ReferenceError: proccess is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-irobot/dist/scripts/getRoombaIP.js:9:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
[06/01/2022, 15:38:17] Error: Command failed: /usr/local/lib/node_modules/homebridge-irobot/dist/scripts/getRoombaIP.js 30F8850492035650
/usr/local/lib/node_modules/homebridge-irobot/dist/scripts/getRoombaIP.js:9
const attempt = proccess.argv[3] || 1;
                ^

ReferenceError: proccess is not defined
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-irobot/dist/scripts/getRoombaIP.js:9:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47

    at checkExecSyncError (node:child_process:826:11)
    at Object.execFileSync (node:child_process:864:15)
    at /usr/local/lib/node_modules/homebridge-irobot/src/getRoombas.ts:18:35
    at Array.forEach (<anonymous>)
    at getRoombas (/usr/local/lib/node_modules/homebridge-irobot/src/getRoombas.ts:16:10)
    at iRobotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-irobot/src/platform.ts:65:36)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-irobot/src/platform.ts:34:12)
    at HomebridgeAPI.emit (node:events:402:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)
```

### Config:

```shell
N/A
```

### Node Version:

N/A

### NPM Version:

N/A

### Homebridge Version:

1.3.9

### Plugin Version:

2.1.7

### Operating System:

Raspberian

**Comment by bloomkd46** [comment]
Thank you so much! I merged the pull request and will publish it as version 2.1.8
