### ISSUE TITLE
Bug Report: Homebridge Crashes when Roomba offline

### ISSUE THREAD

**Issue by rcoletti116** [bloomkd46/homebridge-iRobot#20]
### Describe The Bug:

When Roomba disconnects from network (even briefly) homebridge crashes. Discovered accidentally when robot lost connection briefly, but is repeatable.

### To Reproduce:

Remove active internet connection from Roomba device.

### Expected behavior:

Roomba should not crash homebridge, and also not require connection to internet.

### Logs:

```shell
[06/01/2022, 15:51:41] [redacted] Roomba Rosie  went offline, disconnecting...
[06/01/2022, 15:51:42] Error: HAP Status Error: -70402
    at new HapStatusError (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:15:5)
    at MqttClient.<anonymous> (/usr/local/lib/node_modules/homebridge-irobot/src/platformAccessory.ts:192:13)
    at MqttClient.emit (node:events:390:28)
    at MqttClient._setupReconnect (/usr/local/lib/node_modules/homebridge-irobot/node_modules/mqtt/lib/client.js:730:12)
    at MqttClient.emit (node:events:402:35)
    at TLSSocket.f (/usr/local/lib/node_modules/homebridge-irobot/node_modules/once/once.js:25:25)
    at TLSSocket.onfinish (/usr/local/lib/node_modules/homebridge-irobot/node_modules/end-of-stream/index.js:31:27)
    at TLSSocket.emit (node:events:390:28)
    at finish (node:internal/streams/writable:750:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[06/01/2022, 15:51:42] Got SIGTERM, shutting down Homebridge...
```

### Config:

```shell
{
            "name": "iRobot",
            "email": "redacted",
            "password": "redacted",
            "lowBattery": 10,
            "offAction": "pause:none",
            "status": "phase:run",
            "eveStatus": "phase:charge",
            "bin": "contact",
            "ignoreMultiRoomBin": true,
            "hideStuckSensor": false,
            "disableMultiRoom": false,
            "platform": "iRobotPlatform"
        }
```

### Node Version:

16.13.0

### NPM Version:

8.1.0

### Homebridge Version:

1.3.9

### Plugin Version:

2.1.7

### Operating System:

Raspberian

**Comment by bloomkd46** [comment]
I think I fixed this with version 2.1.9 please reopen this issue if this error resurfaces
