### ISSUE TITLE
Supported Device: 

### ISSUE THREAD

**Issue by spurzack** [bloomkd46/homebridge-iRobot#67]
### Roomba Model:

J7

### Did It Work

No

**Comment by spurzack** [comment]
Receive the following error:

```
Error: spawnSync C:\Users\[username]\AppData\Roaming\npm\node_modules\homebridge-irobot\dist/scripts/getRoombaCredentials.js UNKNOWN
    at Object.spawnSync (node:internal/child_process:1083:20)
    at spawnSync (node:child_process:812:24)
    at Object.execFileSync (node:child_process:858:15)
    at getRoombas (C:\Users\[username]\AppData\Roaming\npm\node_modules\homebridge-irobot\src\getRoombas.ts:8:32)
    at iRobotPlatform.discoverDevices (C:\Users\[username]\AppData\Roaming\npm\node_modules\homebridge-irobot\src\platform.ts:65:36)
    at HomebridgeAPI.<anonymous> (C:\Users\[username]\AppData\Roaming\npm\node_modules\homebridge-irobot\src\platform.ts:34:12)
    at HomebridgeAPI.emit (node:events:390:28)
    at HomebridgeAPI.signalFinished (C:\Users\[username]\AppData\Roaming\npm\node_modules\homebridge\src\api.ts:275:10)
    at ChildBridgeFork.startBridge (C:\Users\[username]\AppData\Roaming\npm\node_modules\homebridge\src\childBridgeFork.ts:173:14)
```
