### ISSUE TITLE
Bug Report: Disabling Unconfigured Roomba

### ISSUE THREAD

**Issue by danielraffel** [bloomkd46/homebridge-iRobot#76]
### Describe The Bug:

Can't manage to successfully configure account with i7 and m6 using homebridge-irobot v2.1.16 on homebridge 1.4.0 running Node.js Version v16.13.2. Have restarted but devices tab in the plugin shows no devices. Expected to see two devices (since both appear to be supported.) Any suggestions?

Startup logs output the following

[iRobot] Initializing iRobotPlatform platform...
[iRobot] Logging into iRobot...
[iRobot] Configuring roomba: Braava jet
[iRobot] Configuring roomba: Roomba
[iRobot] Disabling Unconfigured Roomba: Braava jet

### To Reproduce:

sign-in with account with i7 and m6 using homebridge-irobot v2.1.16 on homebridge 1.4.0 running Node.js Version v16.13.2. On reboot note the plugin shows no devices. 

### Expected behavior:

Expected to see two devices (since both appear to be supported.) 

### Logs:

```shell
[iRobot] Initializing iRobotPlatform platform...
[iRobot] Logging into iRobot...
[iRobot] Configuring roomba: Braava jet
[iRobot] Configuring roomba: Roomba
[iRobot] Disabling Unconfigured Roomba: Braava jet
```

### Config:

```shell
{
            "name": "iRobot",
            "email": "[redacted]",
            "password": "[redacted]",
            "roombas": [
                {
                    "autoConfig": true,
                    "info": {
                        "ver": 2
                    }
                }
            ],
            "manualDiscovery": false,
            "lowBattery": 20,
            "offAction": "pause:dock",
            "status": "cycle:clean",
            "eveStatus": "inverted:cycle:clean",
            "bin": "filter:contact",
            "ignoreMultiRoomBin": true,
            "hideStuckSensor": false,
            "disableMultiRoom": false,
            "platform": "iRobotPlatform"
        }
    ],
```

### Node Version:

16.13.2

### NPM Version:

8.1.2

### Homebridge Version:

2.1.16

### Plugin Version:

2.1.16

### Operating System:

MacOS

**Comment by bloomkd46** [comment]
There is a problem with configuring when it detects a m6. Try the beta version which should let you add both devices.

Let me know if you need help installing it.

**Comment by danielraffel** [comment]
Thanks of the info. I just installed the beta. it seems to work - I guess vacuums appear as fans in HomeKit UI. ;)

Question for ya...

Do you know if/how I could do the following in the Apple Home app

A. set up an automation to run the roomba only on Sat, during the day, when nobody is home

B. set up an automation to run the brava jet after the roomba completes (I presume I should just setup and use a dummy switch for this)

**Comment by danielraffel** [comment]
getting a bunch of errors tonight causing issues with homebridge server 
running: homebridge-irobot v2.1.17-beta.1

[2/6/2022, 9:12:42 PM] [iRobot] Logging into iRobot...
[2/6/2022, 9:12:44 PM] [iRobot] Configuring roomba: Braava jet
[2/6/2022, 9:12:54 PM] [iRobot] Failed to configure roomba: Braava jet see below for details
[2/6/2022, 9:12:54 PM] [iRobot] No Roomba Found With Blid:  [redacted]


[2/6/2022, 9:12:54 PM] [iRobot] Configuring roomba: Roomba
[2/6/2022, 9:13:04 PM] [iRobot] Failed to configure roomba: Roomba see below for details
[2/6/2022, 9:13:04 PM] [iRobot] No Roomba Found With Blid: [redacted]


[2/6/2022, 9:13:04 PM] [iRobot] Disabling Unconfigured Roomba: Braava jet
[2/6/2022, 9:13:04 PM] TypeError: Cannot read properties of undefined (reading 'name')
    at getRoombas (/usr/local/lib/node_modules/homebridge-irobot/src/getRoombas.ts:50:63)
    at iRobotPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-irobot/src/platform.ts:65:36)

**Comment by MaleNurse** [comment]
Updated to 3.0.0 Beta 11 and, while this particular error goes away, I'm now faced with this log section concerning my m6 with my e5 working just fine:

```
[2/20/2022, 8:34:34 PM] [iRobot] [Mabel] Failed To Fetch Robot Status
 Roomba Offline
[2/20/2022, 8:37:30 PM] [homebridge-irobot] This plugin threw an error from the characteristic 'On': Unhandled error thrown inside read handler for characteristic: undefined. See https://git.io/JtMGR for more info.
[2/20/2022, 8:37:33 PM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' was slow to respond! See https://git.io/JtMGR for more info.
[2/20/2022, 8:37:33 PM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[2/20/2022, 8:37:33 PM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' was slow to respond! See https://git.io/JtMGR for more info.
[2/20/2022, 8:37:39 PM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[2/20/2022, 8:37:39 PM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[2/20/2022, 8:37:39 PM] [homebridge-irobot] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
```

**Comment by bloomkd46** [comment]
Please try the latest beta: [![npm](https://img.shields.io/npm/v/homebridge-irobot/beta?label=beta)](https://github.com/bloomkd46/homebridge-iRobot/wiki/Beta-Version)
