### ISSUE TITLE
Support Request: 

### ISSUE THREAD

**Issue by 404d4vdnotfound** [bloomkd46/homebridge-iRobot#86]
### Describe Your Problem:

Homebridge posts the following errors, after rebooting upon configuring the Homebridge iRobot plugin:

### Expected behavior:

Homebridge should startup successfully, and no errors should occur.

### Logs:

```shell
[2/11/2022, 9:17:23 AM] [iRobot] Logging into iRobot...
[2/11/2022, 9:17:23 AM] Error: spawnSync C:\Users\VMUS3R\AppData\Roaming\npm\node_modules\homebridge-irobot\dist/scripts/getRoombaCredentials.js UNKNOWN
    at Object.spawnSync (node:internal/child_process:1111:20)
    at spawnSync (node:child_process:814:24)
    at Object.execFileSync (node:child_process:860:15)
    at getRoombas (C:\Users\VMUS3R\AppData\Roaming\npm\node_modules\homebridge-irobot\src\getRoombas.ts:12:34)
    at iRobotPlatform.discoverDevices (C:\Users\VMUS3R\AppData\Roaming\npm\node_modules\homebridge-irobot\src\platform.ts:65:36)
    at HomebridgeAPI.<anonymous> (C:\Users\VMUS3R\AppData\Roaming\npm\node_modules\homebridge-irobot\src\platform.ts:34:12)
    at HomebridgeAPI.emit (node:events:532:35)
    at HomebridgeAPI.signalFinished (C:\Users\VMUS3R\AppData\Roaming\npm\node_modules\homebridge\src\api.ts:275:10)
    at Server.start (C:\Users\VMUS3R\AppData\Roaming\npm\node_modules\homebridge\src\server.ts:173:14)
[2/11/2022, 9:17:23 AM] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[2/11/2022, 9:17:28 AM] [HB Supervisor] Restarting Homebridge...
```

### Config:

```shell
{
    "bridge": {
        "name": "Homebridge 3FB3",
        "username": "0E:25:97:62:3F:B3",
        "port": 51102,
        "pin": "568-24-971",
        "advertiser": "ciao"
    },
    "accessories": [
        {
            "name": "Babysitter Shim",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "accessory": "DummySwitch"
        },
        {
            "name": "Alarm Shim",
            "stateful": true,
            "reverse": false,
            "time": 1000,
            "resettable": false,
            "accessory": "DummySwitch"
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "dbrownhill@gmail.com",
                "password": "D1g1c0nf",
                "countryCode": "1",
                "platform": "tuya",
                "pollingInterval": 1200
            },
            "defaults": [
                {
                    "id": "Pantry",
                    "device_type": "light",
                    "min_brightness": "0",
                    "max_brightness": "100",
                    "light_characteristics": [
                        "Brightness",
                        "Color"
                    ]
                },
                {
                    "id": "Back Patio",
                    "device_type": "light",
                    "min_brightness": "0",
                    "max_brightness": "100",
                    "light_characteristics": [
                        "Brightness",
                        "Color"
                    ]
                },
                {
                    "id": "Living Room East",
                    "device_type": "light",
                    "min_brightness": "0",
                    "max_brightness": "100",
                    "light_characteristics": [
                        "Brightness",
                        "Color"
                    ]
                },
                {
                    "id": "Living Room West",
                    "device_type": "light",
                    "min_brightness": "0",
                    "max_brightness": "100",
                    "light_characteristics": [
                        "Brightness",
                        "Color"
                    ]
                },
                {
                    "id": "Master Back Deck",
                    "device_type": "light",
                    "min_brightness": "0",
                    "max_brightness": "100",
                    "light_characteristics": [
                        "Brightness",
                        "Color"
                    ]
                },
                {
                    "id": "Back Deck South",
                    "device_type": "light",
                    "min_brightness": "0",
                    "max_brightness": "100",
                    "light_characteristics": [
                        "Brightness",
                        "Color"
                    ]
                },
                {
                    "id": "Back Deck North",
                    "device_type": "light",
                    "min_brightness": "0",
                    "max_brightness": "100",
                    "light_characteristics": [
                        "Brightness",
                        "Color"
                    ]
                }
            ],
            "scenes": true,
            "platform": "TuyaWebPlatform"
        },
        {
            "name": "Meross",
            "username": "dbrownhill@gmail.com",
            "password": "D1g1c0nf",
            "connection": "default",
            "ignoreHKNative": true,
            "singleDevices": [
                {
                    "name": "Back Patio String Lights"
                }
            ],
            "platform": "Meross"
        },
        {
            "name": "iRobot",
            "email": "dbrownhill@gmail.com",
            "password": "D1g1c0nf",
            "roombas": [
                {
                    "autoConfig": true,
                    "info": {
                        "ver": 2
                    }
                }
            ],
            "manualDiscovery": false,
            "lowBattery": 20,
            "offAction": "pause:dock",
            "status": "cycle:clean",
            "eveStatus": "inverted:cycle:clean",
            "bin": "filter:contact",
            "ignoreMultiRoomBin": true,
            "hideStuckSensor": false,
            "disableMultiRoom": false,
            "platform": "iRobotPlatform"
        }
    ]
}
```

### Node Version:

16.14.0

### NPM Version:

8.3.1

### Homebridge Version:

1.4.0

### Plugin Version:

2.1.16

### Operating System:

Windows

**Comment by bloomkd46** [comment]
I apologize, this is a known issue. the plugin doesn't currently work on windows due to the fact that their file paths use \'s instead of /'s. I will let you know tomorrow when I release the first beta for version 3 which will fix this problem. sorry for the inconvenience.

**Comment by bloomkd46** [comment]
Please try the latest beta: [![npm](https://img.shields.io/npm/v/homebridge-irobot/beta?label=beta)](https://github.com/bloomkd46/homebridge-iRobot/wiki/Beta-Version)
