### ISSUE TITLE
Bug Report: Braava not working in homekit automations 

### ISSUE THREAD

**Issue by mikeare123** [bloomkd46/homebridge-iRobot#87]
### Describe The Bug:

Hello, I just installed the latest beta who can support my roomba i7 and braava m6. I can find great both now on my homekit. 
I make automation when the roomba starts at night to turn on some lights works like a charm! But in the same automation but for brava automation not working. I find out to work I have to open home app! In roomba and other equipment I don't need to open the app. Maybe is because is beta?
Keep the great work. Waiting for your fix! 

I run it on raspberry pi 4 with homebridge 

### To Reproduce:

I don't know 

### Expected behavior:

Don't know 

### Logs:

```shell
Don't know
```

### Config:

```shell
Don't know
```

### Node Version:

Node -v

### NPM Version:

Npm -v

### Homebridge Version:

Latest 

### Plugin Version:

Latest beta 

### Operating System:

Other

**Comment by bloomkd46** [comment]
Do you have a home hub set up?

**Comment by bloomkd46** [comment]
Ex. HomePod, HomePod mini, or Apple TV

**Comment by mikeare123** [comment]
Yes i have homepod mini everything up to date. All automations working fine including roomba with the same plugin. Only the braava needs me to open home app so automations for braava will work.

**Comment by bloomkd46** [comment]
Ok, that is really weird. Tomorrow I will be releasing beta's for version 3 which might solve this problem. I will let you know when I publish a semi-stable beta

**Comment by mikeare123** [comment]
Ok please release it as soon as possible and try it cause I really need this feature as irobot work with cameras so in the night you must open a light in room. 
I have 2 in the same account one roomba and one braava. Automations in roomba works great

**Comment by mikeare123** [comment]
Hello i installed the latest bets now and nothing works doesn't find at all the roomba and braava. 
This is the error on homebridge 

[14/02/2022, 07:41:26] [iRobot] Adding new accessory: Braava jet
[14/02/2022, 07:41:26] [iRobot] TypeError: this.platform.config.sensors is not iterable
    at new iRobotPlatformAccessoryV3 (/usr/local/lib/node_modules/homebridge-irobot/src/V2/platformAccessory.ts:390:47)
    at /usr/local/lib/node_modules/homebridge-irobot/src/V2/platform.ts:126:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)


I have to go back to stable but now I don't have the braava

**Comment by bloomkd46** [comment]
Please delete your config when upgrading because the configuration options change

**Comment by mikeare123** [comment]
I do it already and same thing. Also Uninstall and install again same thing. I try to add sensors in settings page logs me in but after 1 minute it says offline and don't work. 

What can I do?

**Comment by mikeare123** [comment]
Hello again. From the version 3 I never achieve connection to irobot . All the beta versions shows in log my brava and roomba as offline every 5 seconds. When I restart homebridge I can I see that plug-in adds my accessories but after one minute start every 5 seconds to show them offline. 

I never achieve to connect on version 3. What happened?.also remove config again the same

**Comment by bloomkd46** [comment]
Please try the latest beta: [![npm](https://img.shields.io/npm/v/homebridge-irobot/beta?label=beta)](https://github.com/bloomkd46/homebridge-iRobot/wiki/Beta-Version)
