### ISSUE TITLE
Support Request:  No Devices Detected after the iRobot Account info entered

### ISSUE THREAD

**Issue by wonghc1** [bloomkd46/homebridge-iRobot#89]
### Describe Your Problem:

I already restart everything, my j7+ and m6 cannot be detected

### Logs:

```shell
[2/12/2022, 10:34:05 AM] [Config] Initializing config platform...
[2/12/2022, 10:34:05 AM] [Config] Running in Service Mode
[2/12/2022, 10:34:05 AM] [iRobot] Initializing iRobotPlatform platform...
[2/12/2022, 10:34:05 AM] [iRobot] Logging into iRobot...
[2/12/2022, 10:34:06 AM] [iRobot] Configuring roomba: Braava jet M6
[2/12/2022, 10:34:07 AM] [iRobot] Configuring roomba: Roomba J7+
[2/12/2022, 10:34:07 AM] [iRobot] Disabling Unconfigured Roomba: Braava jet M6
Setup Payload:

Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    
    └────────────┘     
                       
[2/12/2022, 10:34:07 AM] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge ) is running on port 51949.
```

### Config:

```shell
{
    "bridge": {
        "name": "Homebridge X",
        "username": "X",
        "port": X,
        "pin": "X"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": X,
            "platform": "config"
        },
        {
            "name": "iRobot",
            "email": "X@gmail.com",//privacy issues
            "password": "X",//Hidden
            "roombas": [
                {
                    "autoConfig": true,
                    "info": {
                        "ver": 2
                    }
                }
            ],
            "manualDiscovery": false,
            "lowBattery": 20,
            "offAction": "pause:dock",
            "status": "cycle:clean",
            "eveStatus": "inverted:cycle:clean",
            "bin": "filter:contact",
            "ignoreMultiRoomBin": true,
            "hideStuckSensor": false,
            "disableMultiRoom": false,
            "platform": "iRobotPlatform"
        }
    ]
}
```

### Node Version:

16.14

### NPM Version:

8.3.1

### Homebridge Version:

1.4

### Plugin Version:

homebridge-irobot v2.1.16

### Operating System:

MacOS

**Comment by bloomkd46** [comment]
Please install the latest beta. This is a known bug that I will fix later today. For now just install the latest beta.

**Comment by franciswernet** [comment]
@bloomkd46 I installed the beta but still I'm unable to add my M6

**Comment by bloomkd46** [comment]
What do the logs say now?

**Comment by wonghc1** [comment]
Updated to beta solves the issue, but there is no room by room support for M6

**Comment by wonghc1** [comment]
2.1.17 solved, but 3.0 beta does not solved 
[2/14/2022, 12:08:56 AM] [iRobot] Adding new accessory: Braava jet M6
[2/14/2022, 12:08:57 AM] [iRobot] TypeError: this.platform.config.sensors is not iterable
    at new iRobotPlatformAccessoryV3 (/usr/local/lib/node_modules/homebridge-irobot/src/V2/platformAccessory.ts:390:47)
    at /usr/local/lib/node_modules/homebridge-irobot/src/V2/platform.ts:126:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2/14/2022, 12:11:00 AM] [Homebridge UI] [homebridge-irobot] Terminating child process...
[2/14/2022, 12:11:00 AM] [Homebridge UI] [homebridge-irobot] Child process ended

**Comment by wonghc1** [comment]
> Please install the latest beta. This is a known bug that I will fix later today. For now just install the latest beta.

beta 3.0 still have the bug , m6 and j7 still not detected. they work in 2.1.17 beta


[2/14/2022, 12:08:56 AM] [iRobot] Adding new accessory: Braava jet M6
[2/14/2022, 12:08:57 AM] [iRobot] TypeError: this.platform.config.sensors is not iterable
    at new iRobotPlatformAccessoryV3 (/usr/local/lib/node_modules/homebridge-irobot/src/V2/platformAccessory.ts:390:47)
    at /usr/local/lib/node_modules/homebridge-irobot/src/V2/platform.ts:126:15
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2/14/2022, 12:11:00 AM] [Homebridge UI] [homebridge-irobot] Terminating child process...
[2/14/2022, 12:11:00 AM] [Homebridge UI] [homebridge-irobot] Child process ended

**Comment by wonghc1** [comment]
also no sensor is detected in beta 3

**Comment by bloomkd46** [comment]
Please delete the iRobot config then try again. The latest beta changes how you configure the Roomba

**Comment by wonghc1** [comment]
> Please delete the iRobot config then try again. The latest beta changes how you configure the Roomba

I already deleted old config. and still no device detected in beta 3

**Comment by agrajag42a** [comment]
same problem with Braava Jet M6 in 2.1.16

**Comment by bloomkd46** [comment]
Please try the latest beta: [![npm](https://img.shields.io/npm/v/homebridge-irobot/beta?label=beta)](https://github.com/bloomkd46/homebridge-iRobot/wiki/Beta-Version)
